### ISSUE TITLE
Is SnapEngage supported?

### ISSUE THREAD

**Issue by johnmathews** [jazzband/django-analytical#166]
Its listed in your readme, but not in your docs on the installation and config page.

**Comment by bittner** [comment]
Yes, it's in the code: https://github.com/jazzband/django-analytical/search?q=SnapEngage

It's also covered by [our documentation](https://django-analytical.readthedocs.io/en/latest/services/snapengage.html).

I hope that helps.

**Comment by bittner** [comment]
@jcassee Do you happen to know why this service is not mentioned in the [Installation and configuration](https://django-analytical.readthedocs.io/en/latest/install.html) section?

The [SNAPENGAGE_WIDGET_ID](https://django-analytical.readthedocs.io/en/latest/services/snapengage.html#setting-the-widget-id) needs to be set, so this seems to have been missed out in the docs. Or is there something @johnmathews and I have overlooked?

**Comment by bittner** [comment]
Thanks @johnmathews for reporting this problem! :medal_sports:
