### ISSUE TITLE
Clickmap link in README links to spammy website

### ISSUE THREAD

**Issue by kobus-v-schoor** [jazzband/django-analytical#182]
The Clickmap link in the readme (http://getclickmap.com/) is currently redirecting to a spammy betting website

**Comment by bittner** [comment]
Thanks for reporting this! Do you happen to know which is the correct URL of that service? Is it www.clickmap.ch?

**Comment by kobus-v-schoor** [comment]
Unfortunately I have no idea, haven't heard of them before but www.clickmap.ch looks like it could be the service (although it also looks a bit dodgy) - maybe the company closed down? I'm unable to find anything to back this up though
