### ISSUE TITLE
Respecting Consent ( Possible fix for #141 )

### ISSUE THREAD

**Issue by SilverStrings024** [jazzband/django-analytical#192]
I saw #141 asking about how to respect the users choice when it comes to tracking and I was wondering why we can't just define a dotted path to a function that will tell if the user accepted or rejected tracking in settings.py and make the template tag comment out the tracking code if the function returns False like it does if the users ip address is an internal ip.

It's an easy, fast, non-obstructive fix for something I would imagine a lot of us need (me included).

**Comment by bittner** [comment]
Sounds like a good idea!

If you feel that #142 is not good enough of a PR do you want to try and open an alternative one as a contribution?

**Comment by SilverStrings024** [comment]
> Sounds like a good idea!
> 
> If you feel that #142 is not good enough of a PR do you want to try and open an alternative one as a contribution?

Sure! I'll take a look at the current code and see what I can come up with!

**Comment by SilverStrings024** [comment]
@bittner I finished the PR but git is saying I'm not allowed to push?

**Comment by bittner** [comment]
You need create your own fork of this repository, push the changes to your own fork (that will work) and place a PR from there.

**Comment by SilverStrings024** [comment]
> You need create your own fork of this repository, push the changes to your own fork (that will work) and place a PR from there.

OOOOOOH *sigh* wow. Alright, thank you. I came up with a much better solution. Once I get this working, I'll be pushing

**Comment by SilverStrings024** [comment]
PR #193 Takes care of this
