### ISSUE TITLE
Allow to set a custom location for google analytics js - support for proxy

### ISSUE THREAD

**Issue by kevin-olbrich** [jazzband/django-analytical#212]
Hi!

It would be very convenient to be able to change the JS import path / url to support proxying GA data:
https://gist.github.com/paivaric/211ca15afd48c5686226f5f747539e8b

**Comment by bittner** [comment]
Feel free to [make the code parametrizable](https://github.com/jazzband/django-analytical/blob/main/analytical/templatetags/google_analytics_js.py#L24-L34) and submit a PR for the required change!

**Comment by kevin-olbrich** [comment]
Ok, I'll have a look.
