### ISSUE TITLE
Latest docs must build from `main` (not `master`)

### ISSUE THREAD

**Issue by bittner** [jazzband/django-analytical#221]
As can be seen on RTD, the "latest" docs [are configured to build](https://readthedocs.org/projects/django-analytical/versions/) from the `master` branch. However, we switched the default branch to `main` with #204 half a year ago. We apparently overlooked that updating the RTD configuration settings was necessary, too.

@jcassee Can you update the value on RTD, please, and trigger a build of the latest docs?

**Comment by jcassee** [comment]
![afbeelding](https://user-images.githubusercontent.com/20749/180175043-9603b9c6-dc60-4446-9be5-ee6f52eb0369.png)

Anyway, I set it to "main".

**Comment by jcassee** [comment]
I also made @bittner maintainer at RTD. Thanks for noticing the problem.

**Comment by bittner** [comment]
Great! Thanks, Joost! :1st_place_medal:
