### ISSUE TITLE
Usage in Docker

### ISSUE THREAD

**Issue by BenAkko** [jazzband/django-analytical#228]
Hi all,

Thanks for producing a great package!

I'm wanting to use this package with Clicky inside docker (from cookiecutter-django), but I'm not sure how to do the initial python setup within my docker container.

Has anyone used this package inside a docker container, and if so, how did you do the initial install?

Many thanks for any help anyone can offer!

**Comment by bittner** [comment]
Like any Django app you integrate it in your Django project. If you manage to install your Django project in a container image (e.g. Docker) you're done. Just try it and you'll see it's not magic!

If you look at an existing `Dockerfile` that hosts a Django project you'll likely see lines like these:

```
COPY requirements.txt ./
RUN pip install -r requirements.txt
```

This is a very common way to install all you project's dependencies, which would also cover *django-analytical* if you use it.

In a more advanced approach you'd package your Django project up as a Python package first and install it directly in the `Dockerfile`. But that's a topic for another day assuming you are only starting with Docker now.

**Comment by bittner** [comment]
This question is not specific to a feature of this project, hence closing the issue.

You may look for tutorials on how to deploy a Django project using Docker.
